/* orm-driver-connection.h
 *
 * Copyright 2025 Zach Podbielniak
 *
 * This file is part of orm-glib.
 *
 * orm-glib is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * orm-glib is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with orm-glib.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#ifndef ORM_DRIVER_CONNECTION_H
#define ORM_DRIVER_CONNECTION_H

#if !defined(ORM_INSIDE) && !defined(ORM_COMPILATION)
#error "Only <orm.h> can be included directly."
#endif

#include <glib-object.h>
#include "../core/orm-enums.h"
#include "../core/orm-value.h"
#include "orm-driver-result.h"

G_BEGIN_DECLS

#define ORM_TYPE_DRIVER_CONNECTION (orm_driver_connection_get_type ())

G_DECLARE_DERIVABLE_TYPE (OrmDriverConnection, orm_driver_connection, ORM, DRIVER_CONNECTION, GObject)

/*
 * OrmDriverConnectionClass:
 * @close: Disconnect from the database
 * @execute: Run a statement that returns no rows
 * @query: Run a statement that returns rows
 * @get_last_insert_id: Row id generated by the last INSERT
 * @get_changes: Rows affected by the last statement
 * @set_isolation_level: Apply a transaction isolation level
 * @interrupt: Ask the backend to abandon the statement in flight
 *
 * One live connection to a database, as the backend exposes it.
 *
 * @interrupt is the one method with a threading contract: it may be
 * called from a thread other than the one running the query, because
 * that is the only moment at which cancelling is useful. Backends whose
 * cancel primitive is not safe that way must leave @interrupt
 * unimplemented rather than approximate it -- the default returns
 * %ORM_ERROR_NOT_SUPPORTED, and callers fall back to abandoning the
 * result.
 */
struct _OrmDriverConnectionClass
{
    GObjectClass parent_class;

    void              (*close)               (OrmDriverConnection *self);
    gboolean          (*execute)             (OrmDriverConnection  *self,
                                              const gchar          *sql,
                                              GList                *params,
                                              GError              **error);
    OrmDriverResult * (*query)               (OrmDriverConnection  *self,
                                              const gchar          *sql,
                                              GList                *params,
                                              OrmQueryFlags         flags,
                                              GError              **error);
    gint64            (*get_last_insert_id)  (OrmDriverConnection *self);
    gint              (*get_changes)         (OrmDriverConnection *self);
    gboolean          (*set_isolation_level) (OrmDriverConnection  *self,
                                              OrmIsolationLevel     level,
                                              gboolean              for_next_transaction,
                                              GError              **error);
    gboolean          (*interrupt)           (OrmDriverConnection  *self,
                                              GError              **error);

    /*< private >*/
    gpointer _reserved[8];
};

/*
 * orm_driver_connection_close:
 * @self: An #OrmDriverConnection
 *
 * Disconnects from the database.  Idempotent.
 */
void orm_driver_connection_close (OrmDriverConnection *self);

/*
 * orm_driver_connection_execute:
 * @self: An #OrmDriverConnection
 * @sql: The statement
 * @params: (element-type OrmValue) (nullable): Bound parameters
 * @error: Return location for error
 *
 * Runs a statement that returns no rows.
 *
 * Returns: %TRUE on success
 */
gboolean orm_driver_connection_execute (OrmDriverConnection  *self,
                                        const gchar          *sql,
                                        GList                *params,
                                        GError              **error);

/*
 * orm_driver_connection_query:
 * @self: An #OrmDriverConnection
 * @sql: The statement
 * @params: (element-type OrmValue) (nullable): Bound parameters
 * @flags: Query flags
 * @error: Return location for error
 *
 * Runs a statement that returns rows.
 *
 * Returns: (transfer full) (nullable): A new #OrmDriverResult, or %NULL
 */
OrmDriverResult * orm_driver_connection_query (OrmDriverConnection  *self,
                                               const gchar          *sql,
                                               GList                *params,
                                               OrmQueryFlags         flags,
                                               GError              **error);

/*
 * orm_driver_connection_get_last_insert_id:
 * @self: An #OrmDriverConnection
 *
 * Returns: The row id generated by the last INSERT, or 0
 */
gint64 orm_driver_connection_get_last_insert_id (OrmDriverConnection *self);

/*
 * orm_driver_connection_get_changes:
 * @self: An #OrmDriverConnection
 *
 * Returns: The number of rows affected by the last statement
 */
gint orm_driver_connection_get_changes (OrmDriverConnection *self);

/*
 * orm_driver_connection_set_isolation_level:
 * @self: An #OrmDriverConnection
 * @level: The isolation level
 * @for_next_transaction: %TRUE to affect only the next transaction rather
 *   than the whole session
 * @error: Return location for error
 *
 * Returns: %TRUE on success
 */
gboolean orm_driver_connection_set_isolation_level (OrmDriverConnection  *self,
                                                    OrmIsolationLevel     level,
                                                    gboolean              for_next_transaction,
                                                    GError              **error);

/*
 * orm_driver_connection_interrupt:
 * @self: An #OrmDriverConnection
 * @error: Return location for error
 *
 * Asks the backend to abandon the statement currently in flight.  May be
 * called from another thread.  Backends that cannot do this safely fail
 * with %ORM_ERROR_NOT_SUPPORTED.
 *
 * Returns: %TRUE if the backend was asked to stop
 */
gboolean orm_driver_connection_interrupt (OrmDriverConnection  *self,
                                          GError              **error);

G_END_DECLS

#endif /* ORM_DRIVER_CONNECTION_H */
